import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'msedge'});
try{for(const width of [390,1440]){const context=await browser.newContext({viewport:{width,height:950},hasTouch:width===390});await context.addInitScript(()=>localStorage.setItem('today-cloud-config',JSON.stringify({url:'',key:''})));const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5173/');await page.locator('#daily-input').fill('读完一篇论文');await page.locator('#daily-form button').click();await page.getByText('读完一篇论文',{exact:true}).waitFor();await page.locator('#daily-list .item-check').click();await page.waitForFunction(()=>document.querySelector('#daily-list .done'));
await page.locator('#next').click();assert.equal(await page.locator('#daily-list .list-row').count(),0);await page.locator('#today').click();assert.equal(await page.locator('#daily-list .list-row').count(),1);
for(const title of ['九月规划','论文规划','完整计划']){await page.locator('#new-board').click();await page.locator('#edit-title').fill(title);await page.locator('#edit-save').click();await page.getByRole('heading',{name:title,exact:true}).waitFor();}
const first=page.locator('.board').first();await first.locator('input').fill('完成实验 <重要>');await first.locator('form button').click();await page.getByText('完成实验 <重要>',{exact:true}).waitFor();await first.locator('[data-edit]').click();await page.locator('#edit-title').fill('完成主要实验');await page.locator('#edit-save').click();await page.getByText('完成主要实验',{exact:true}).waitFor();await page.reload();await page.getByText('完成主要实验',{exact:true}).waitFor();assert.equal(await page.locator('.board').count(),3);assert.equal(await page.locator('#daily-list .done').count(),1);
await page.locator('#boards').evaluate(el=>el.scrollLeft=200);if(width===390)assert.ok(await page.locator('#boards').evaluate(el=>el.scrollLeft>0));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('#boards').evaluate(el=>el.scrollLeft=0);await page.screenshot({path:width===390?'preview-checklists-mobile.png':'preview-checklists-desktop.png',fullPage:true});
await first.locator('[data-board-edit]').click();page.once('dialog',d=>d.accept());await page.locator('#delete-board').click();await page.waitForFunction(()=>document.querySelectorAll('.board').length===2);await page.locator('#settings').click();const download=page.waitForEvent('download');await page.locator('#export').click();assert.ok((await download).suggestedFilename().endsWith('.json'));assert.deepEqual(errors,[]);console.log('PASS checklists '+width+'px: daily history, completion, projects, items, editing, persistence, swipe, delete, export');await context.close();}}finally{await browser.close();}
