import {localDate,shiftDate,minutes} from './model.js';
export const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function weekDays(day,mode){const offset=new Date(day+'T12:00:00').getDay();const first=mode==='day'?day:shiftDate(day,-offset);return Array.from({length:mode==='day'?1:7},(_,i)=>shiftDate(first,i));}
export function timeString(n){return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;}
export function layoutEvents(events){const sorted=[...events].sort((a,b)=>minutes(a.start)-minutes(b.start)||minutes(b.end)-minutes(a.end));const groups=[];for(const event of sorted){let group=groups.at(-1);if(!group||minutes(event.start)>=group.end){group={end:0,items:[],lanes:[]};groups.push(group);}let lane=group.lanes.findIndex(end=>end<=minutes(event.start));if(lane<0)lane=group.lanes.length;group.lanes[lane]=minutes(event.end);group.end=Math.max(group.end,minutes(event.end));group.items.push({...event,lane});}return groups.flatMap(g=>g.items.map(e=>({...e,columns:g.lanes.length})));}
export function mountCalendar(){
document.querySelector('.shell').innerHTML=`<header class="calendar-top"><a class="calendar-brand" href="./"><span class="calendar-logo">今</span><strong>今日</strong><span>Calendar</span></a><button id="today">今天</button><div class="week-nav"><button id="prev" aria-label="上一页">‹</button><button id="next" aria-label="下一页">›</button></div><h1 id="date-label"></h1><div class="top-actions"><select id="view-mode" aria-label="日历视图"><option value="week">周视图</option><option value="day">日视图</option></select><button id="account">连接云端</button><button id="settings" aria-label="同步与设置">⚙</button></div></header><aside class="task-sidebar"><button id="add" class="create-event">＋ 创建时间规划</button><section class="mini-calendar"><div class="mini-heading"><strong id="mini-title"></strong><div><button id="mini-prev" aria-label="上个月">‹</button><button id="mini-next" aria-label="下个月">›</button></div></div><div class="mini-week"><span>日</span><span>一</span><span>二</span><span>三</span><span>四</span><span>五</span><span>六</span></div><div id="mini-days"></div><input type="date" id="day" aria-label="跳转日期"></section><section class="tasks-section"><div class="task-heading"><h2>Tasks <span id="task-count">0</span></h2><span>无需安排时间</span></div><form id="task-form"><input id="task-title" aria-label="新任务" maxlength="120" required placeholder="添加一个待办任务…" autocomplete="off"><button type="submit" aria-label="添加任务">＋</button></form><div id="tasks"></div></section><div class="sidebar-bottom"><span class="small-dot"></span><span id="sync" role="status">本机保存</span><p>先记下要做的事，再为它留出时间。</p></div></aside><main class="calendar-main"><div class="calendar-days" id="calendar-days"></div><div class="calendar-scroll" id="calendar-scroll"><div class="calendar-grid" id="plans"></div></div><div class="calendar-hint">点击空白处添加规划 · 电脑可拖选一段时间<span id="zone"></span></div></main></div>`;
}
export function renderCalendar({day,plans,user,cloud,mode,tasks,miniMonth}){
 const $=id=>document.getElementById(id),days=weekDays(day,mode),today=localDate();
 $('day').value=day;$('view-mode').value=mode;$('date-label').textContent=new Date(day+'T12:00:00').toLocaleDateString('zh-CN',{year:'numeric',month:'long'});
 $('account').textContent=user?'已登录':cloud?'登录同步':'连接云端';$('login').hidden=!!user;$('logout').hidden=!user;$('import').hidden=!user;
 $('calendar-days').style.setProperty('--days',days.length);$('plans').style.setProperty('--days',days.length);
 const weekdays=['日','一','二','三','四','五','六'];$('calendar-days').innerHTML='<div class="timezone">时间</div>'+days.map(d=>`<button class="day-header ${d===today?'is-today':''} ${d===day?'selected-day':''}" data-day="${d}"><span>周${weekdays[new Date(d+'T12:00:00').getDay()]}</span><strong>${Number(d.slice(-2))}</strong></button>`).join('');
 const hours=Array.from({length:24},(_,h)=>`<span style="top:${h*64}px">${String(h).padStart(2,'0')}:00</span>`).join('');const now=new Date();const current=now.getHours()*60+now.getMinutes();
 $('plans').innerHTML=`<div class="hour-labels">${hours}</div>`+days.map(d=>`<div class="day-column ${d===today?'today-column':''}" data-day="${d}" aria-label="${d} 时间表">${Array.from({length:24},(_,h)=>`<button class="hour-slot" style="top:${h*64}px" data-day="${d}" data-minute="${h*60}" aria-label="${d} ${String(h).padStart(2,'0')}:00 添加规划"></button>`).join('')}${layoutEvents(plans.filter(p=>p.day===d)).map(p=>`<button class="calendar-event ${p.done?'event-done':''} cat-${safe(p.category)}" data-action="edit" data-id="${safe(p.id)}" style="top:${minutes(p.start)/60*64}px;height:${Math.max(18,(minutes(p.end)-minutes(p.start))/60*64-2)}px;left:calc(${p.lane/p.columns*100}% + 3px);width:calc(${100/p.columns}% - 6px)" aria-label="编辑 ${safe(p.title)} ${p.start} 至 ${p.end}"><strong>${p.done?'✓ ':''}${safe(p.title)}</strong><span>${p.start} – ${p.end}</span></button>`).join('')}${d===today?`<div class="now-line" style="top:${current/60*64}px"><i></i></div>`:''}</div>`).join('');
 $('zone').textContent=Intl.DateTimeFormat().resolvedOptions().timeZone;
 const month=new Date(miniMonth+'-01T12:00:00');$('mini-title').textContent=month.toLocaleDateString('zh-CN',{year:'numeric',month:'long'});const first=shiftDate(miniMonth+'-01',-month.getDay());$('mini-days').innerHTML=Array.from({length:42},(_,i)=>{const d=shiftDate(first,i);return `<button data-day="${d}" class="${d===today?'mini-today':''} ${d===day?'mini-selected':''} ${d.slice(0,7)!==miniMonth?'muted-day':''}" aria-label="${d}">${Number(d.slice(-2))}</button>`;}).join('');
 $('task-count').textContent=tasks.filter(t=>!t.done).length;
 $('tasks').innerHTML=tasks.length?[...tasks].sort((a,b)=>Number(a.done)-Number(b.done)).map(t=>`<div class="task-row ${t.done?'task-done':''}"><button class="task-check" data-task-action="toggle" data-id="${safe(t.id)}" aria-label="${t.done?'取消完成':'完成任务'} ${safe(t.title)}" aria-pressed="${t.done}">${t.done?'✓':''}</button><span>${safe(t.title)}</span><button class="task-edit" data-task-action="edit" data-id="${safe(t.id)}" aria-label="编辑任务 ${safe(t.title)}">✎</button><button class="task-delete" data-task-action="delete" data-id="${safe(t.id)}" aria-label="删除任务 ${safe(t.title)}">×</button></div>`).join(''):'<p class="tasks-empty">把想做的事先记在这里。<br>不需要日期，也不需要时间。</p>';
}
export function bindSelection(open){let selection=null;const grid=document.getElementById('plans');
 grid.addEventListener('pointerdown',e=>{if(e.button!==0||e.pointerType==='touch'||e.target.closest('.calendar-event'))return;const column=e.target.closest('.day-column');if(!column)return;const minute=Math.min(1425,Math.max(0,Math.floor((e.clientY-column.getBoundingClientRect().top)/64*4)*15));selection={column,day:column.dataset.day,start:minute,end:Math.min(1439,minute+30),origin:e.clientY,moved:false};column.setPointerCapture(e.pointerId);const block=document.createElement('div');block.className='selection-block';column.append(block);e.preventDefault();});
 grid.addEventListener('pointermove',e=>{if(!selection)return;const minute=Math.min(1425,Math.max(0,Math.floor((e.clientY-selection.column.getBoundingClientRect().top)/64*4)*15));selection.moved ||= Math.abs(e.clientY-selection.origin)>5;selection.end=Math.min(1439,minute+15);const top=Math.min(selection.start,minute),bottom=Math.max(selection.start+15,selection.end);const block=selection.column.querySelector('.selection-block');block.style.top=top/60*64+'px';block.style.height=(bottom-top)/60*64+'px';block.textContent=timeString(top)+' – '+timeString(bottom);});
 grid.addEventListener('pointerup',()=>{if(!selection)return;const s=selection;selection=null;s.column.querySelector('.selection-block')?.remove();if(s.moved){const start=Math.min(s.start,s.end-15),end=Math.max(s.start+15,s.end);open(s.day,timeString(start),timeString(end));grid.dataset.ignoreClick='yes';}else{open(s.day,timeString(s.start),timeString(Math.min(1439,s.start+60)));grid.dataset.ignoreClick='yes';}});
 grid.addEventListener('pointercancel',()=>{selection?.column.querySelector('.selection-block')?.remove();selection=null;});
 grid.addEventListener('click',e=>{if(grid.dataset.ignoreClick){delete grid.dataset.ignoreClick;return;}if(e.target.closest('.calendar-event'))return;const slot=e.target.closest('.hour-slot');if(slot){const n=Number(slot.dataset.minute);open(slot.dataset.day,timeString(n),timeString(Math.min(1439,n+60)));}});
}

