export function createStore(client,storage){
 const key='today-checklists-v1';
 const read=()=>JSON.parse(storage.getItem(key)||'{"boards":[],"items":[]}');
 const tables={boards:'planning_boards',items:'checklist_items'};
 async function list(){if(!client)return read();const results=await Promise.all(Object.values(tables).map(t=>client.from(t).select('*').order('created_at')));for(const r of results)if(r.error)throw Error('请先执行 supabase-checklists.sql，或检查网络：'+r.error.message);return {boards:results[0].data,items:results[1].data};}
 async function save(kind,row,previous){const fields=kind==='boards'?['id','title','color']:['id','title','done','day','board_id'];const clean=Object.fromEntries(fields.filter(k=>row[k]!==undefined).map(k=>[k,row[k]]));if(client){const query=previous?client.from(tables[kind]).update(clean).eq('id',row.id).eq('updated_at',previous.updated_at):client.from(tables[kind]).insert(clean);const {data,error}=await query.select();if(error)throw error;if(!data.length)throw Error('内容已被另一台设备修改，请刷新后重试');return;}const data=read(),index=data[kind].findIndex(x=>x.id===row.id);if(previous&&(index<0||data[kind][index].updated_at!==previous.updated_at))throw Error('内容已被另一窗口修改，请刷新后重试');const record={...clean,created_at:previous?.created_at||new Date().toISOString(),updated_at:crypto.randomUUID()};if(index<0)data[kind].push(record);else data[kind][index]=record;storage.setItem(key,JSON.stringify(data));}
 async function remove(kind,row){if(client){const {data,error}=await client.from(tables[kind]).delete().eq('id',row.id).eq('updated_at',row.updated_at).select('id');if(error)throw error;if(!data.length)throw Error('内容已被修改，请刷新后重试');return;}const data=read();const current=data[kind].find(x=>x.id===row.id);if(!current||current.updated_at!==row.updated_at)throw Error('内容已被修改，请刷新后重试');data[kind]=data[kind].filter(x=>x.id!==row.id);if(kind==='boards')data.items=data.items.filter(x=>x.board_id!==row.id);storage.setItem(key,JSON.stringify(data));}
 return {list,save,remove};
}
