import './checklists.css';
import {cloud,readConfig,saveConfig} from './cloud.js';
import {createStore} from './checklist-store.js';
import {localDate,shiftDate} from './model.js';
const preview=new URLSearchParams(location.search).get('preview')==='1';
const $=id=>document.getElementById(id),store=createStore(preview?null:cloud,preview?sessionStorage:localStorage);
let state={boards:[],items:[]},day=localDate(),busy=false,ready=false,edit=null,requestId=0,timer;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('toast').hidden=true,5000);}
function rows(items){return [...items].sort((a,b)=>Number(a.done)-Number(b.done)).map(item=>`<div class="list-row ${item.done?'done':''}"><button class="item-check" data-toggle="${item.id}" aria-label="${item.done?'取消完成':'完成'} ${esc(item.title)}" aria-pressed="${item.done}">${item.done?'✓':''}</button><span class="item-title">${esc(item.title)}</span><div class="item-actions"><button data-edit="${item.id}" aria-label="编辑 ${esc(item.title)}">✎</button><button data-delete="${item.id}" aria-label="删除 ${esc(item.title)}">×</button></div></div>`).join('');}
function render(){
 const today=localDate(),items=state.items.filter(i=>i.day===day),done=items.filter(i=>i.done).length;
 $('daily-heading').textContent=day===today?'☀ 今日规划':'☀ 当日规划';$('date-label').textContent=new Date(day+'T12:00:00').toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'short'});$('daily-count').textContent=`${items.length} 项计划 · 已完成 ${done} 项`;$('progress').style.width=(items.length?done/items.length*100:0)+'%';
 $('daily-list').innerHTML=rows(items)||'<p class="empty">新的一天，先写下几件想完成的小事吧。</p>';
 const drafts=new Map([...document.querySelectorAll('[data-board-form]')].map(f=>[f.dataset.boardForm,f.elements.title.value]));const active=document.activeElement?.closest('[data-board-form]')?.dataset.boardForm;const caret=document.activeElement?.selectionStart;const scroll=$('boards').scrollLeft;
 $('boards').innerHTML=state.boards.map(board=>{const items=state.items.filter(i=>i.board_id===board.id),done=items.filter(i=>i.done).length;return `<article class="board ${['mint','blue','lavender','sand'].includes(board.color)?board.color:'mint'}"><div class="board-title"><span>▤</span><h3>${esc(board.title)}</h3><button data-board-edit="${board.id}" aria-label="编辑规划 ${esc(board.title)}">···</button></div><p class="board-count">${items.length} 个步骤 · 已完成 ${done} 个</p><div>${rows(items)||'<p class="empty">把大目标拆成一步一步。<br>先写下第一件要做的事。</p>'}</div><form class="add-item" data-board-form="${board.id}"><input name="title" required maxlength="500" aria-label="为${esc(board.title)}添加步骤" placeholder="添加一个步骤…" value="${esc(drafts.get(board.id)||'')}"><button aria-label="添加步骤">＋</button></form></article>`;}).join('')+'<button class="board-placeholder" id="placeholder-board"><strong>＋</strong><span>开始一个新的规划</span><small>例如：本月目标、论文规划、毕业计划</small></button>';
 $('placeholder-board').onclick=()=>openBoard();$('boards').scrollLeft=scroll;
 if(active){const input=document.querySelector(`[data-board-form="${active}"] input`);input?.focus({preventScroll:true});if(input&&caret!==null)input.setSelectionRange(caret,caret);}
 for(const b of document.querySelectorAll('#daily-form button,#new-board,#placeholder-board,[data-board-form] button'))b.disabled=!ready;
}
async function load(){const request=++requestId;try{const data=await store.list();if(request!==requestId)return;state=data;ready=true;$('notice').hidden=!preview;if(preview)$('notice').textContent='本机预览：这里的内容仅用于体验，不会写入共享云端。';$('sync').textContent=preview?'○ 本机预览':cloud?'● 共享清单 · 已同步':'○ 本机保存';render();}catch(e){if(request!==requestId)return;ready=false;$('sync').textContent='尚未同步';$('notice').hidden=false;$('notice').innerHTML=`${esc(e.message)} <a href="https://github.com/MHQQysh/today-planner/blob/checklist-redesign/supabase-checklists.sql" target="_blank" rel="noopener">查看配置文件</a>`;render();}}
async function run(work){if(busy)return;busy=true;try{await work();}catch(e){toast('未保存：'+e.message);}finally{busy=false;}}
async function addItem(title,scope){if(!ready)throw Error('请先完成云端配置');if(!title.trim())return;await store.save('items',{id:crypto.randomUUID(),title:title.trim(),done:false,...scope});}
function openEditor(kind,row){edit={kind,row};$('edit-heading').textContent=kind==='boards'?(row?'编辑规划':'新建规划'):'编辑清单项';$('edit-title').value=row?.title||'';$('edit-title').maxLength=kind==='boards'?120:500;$('color-label').hidden=kind!=='boards';$('delete-board').hidden=kind!=='boards'||!row;$('edit-color').value=row?.color||['mint','blue','lavender','sand'][state.boards.length%4];$('edit-error').textContent='';$('edit-dialog').showModal();$('edit-title').focus();}
function openBoard(){openEditor('boards',null);}
$('new-board').onclick=openBoard;
$('daily-form').onsubmit=e=>{e.preventDefault();const title=$('daily-input').value;run(async()=>{await addItem(title,{day,board_id:null});$('daily-input').value='';await load();});};
$('boards').addEventListener('submit',e=>{const form=e.target.closest('[data-board-form]');if(!form)return;e.preventDefault();const title=form.elements.title.value;run(async()=>{await addItem(title,{day:null,board_id:form.dataset.boardForm});form.elements.title.value='';await load();});});
document.addEventListener('click',e=>{const target=e.target.closest('[data-toggle],[data-edit],[data-delete],[data-board-edit]');if(!target||busy||!ready)return;if(target.dataset.boardEdit){const board=state.boards.find(b=>b.id===target.dataset.boardEdit);if(board)openEditor('boards',board);return;}const id=target.dataset.toggle||target.dataset.edit||target.dataset.delete,item=state.items.find(i=>i.id===id);if(!item)return;if(target.dataset.edit)openEditor('items',item);if(target.dataset.toggle)run(async()=>{await store.save('items',{...item,done:!item.done},item);await load();});if(target.dataset.delete&&confirm(`删除“${item.title}”？`))run(async()=>{await store.remove('items',item);await load();});});
$('edit-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const title=$('edit-title').value.trim();if(!title){$('edit-error').textContent='请填写内容';return;}busy=true;$('edit-save').disabled=true;try{const record=edit.kind==='boards'?{id:edit.row?.id||crypto.randomUUID(),title,color:$('edit-color').value}:{...edit.row,title};await store.save(edit.kind,record,edit.row);$('edit-dialog').close();await load();if(edit.kind==='boards'&&!edit.row)$('boards').scrollTo({left:$('boards').scrollWidth,behavior:'smooth'});}catch(error){$('edit-error').textContent='未保存：'+error.message;}finally{busy=false;$('edit-save').disabled=false;}};
$('delete-board').onclick=()=>{if(!edit?.row||busy)return;const count=state.items.filter(i=>i.board_id===edit.row.id).length;if(confirm(`删除“${edit.row.title}”及其中 ${count} 个步骤？`))run(async()=>{await store.remove('boards',edit.row);$('edit-dialog').close();await load();});};
for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>{if(!busy)$(b.dataset.close).close();};for(const dialog of document.querySelectorAll('dialog'))dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});
for(const [id,delta] of [['prev',-1],['next',1]])$(id).onclick=()=>{day=shiftDate(day,delta);render();};$('today').onclick=()=>{day=localDate();render();};
for(const [id,direction] of [['boards-left',-1],['boards-right',1]])$(id).onclick=()=>$('boards').scrollBy({left:direction*($('boards').querySelector('.board')?.offsetWidth||300),behavior:'smooth'});
$('settings').onclick=()=>{const config=readConfig();$('cloud-url').value=config.url;$('cloud-key').value=config.key;$('settings-dialog').showModal();};$('config-form').onsubmit=e=>{e.preventDefault();try{saveConfig($('cloud-url').value.trim(),$('cloud-key').value.trim());location.reload();}catch(e){toast(e.message);}};$('refresh').onclick=()=>load();
$('export').onclick=()=>run(async()=>{const data=await store.list();const url=URL.createObjectURL(new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),...data},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`规划清单-${localDate()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
window.addEventListener('focus',()=>{if(!busy)load();});window.addEventListener('online',()=>load());window.addEventListener('storage',()=>{if(!cloud&&!busy)load();});setInterval(()=>{if(!document.hidden&&!busy&&!$('edit-dialog').open)load();},15000);
render();await load();
